### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0

### ISSUE THREAD

**Issue by DLuong79** [GWW/sctx#2]
I keep getting this error when running the code from the example, but with my own data swapped in. It's worth noting that it's accompanied by the message, "Only one genoptype found try rescue_genotype to find a second one".

```
IndexError                                Traceback (most recent call last)
Cell In[8], line 23
     21 data.cluster(k=10, threads=THREADS, resolution=0.4, seed=42, min_cells=5)
     22 if data._NL == 1:
---> 23     data.rescue_genotype(out=None, eps=1e-5, upper_mads=10, lower_mads=3)
     24 if data._NL == 1:
     25     print('cannot proceed only one genotype found')

File ~/anaconda3/envs/myenv/lib/python3.12/site-packages/sctx/genotype.py:313, in TxDemulti.rescue_genotype(self, out, eps, upper_mads, lower_mads)
    311 for i, l in zip([0, 1, 3], lnames):
    312     lidx = labels == i
--> 313     axs.scatter(counts[lidx], scores[lidx], s=5, lw=0, edgecolor='k', color=plt.cm.Dark2.colors[i], rasterized=True, label=l)
    314 axs.set_xscale('log')
    315 axs.legend(loc='upper left', bbox_to_anchor=[1.05, 1])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 263 but corresponding boolean dimension is 274
```
Is this simply because sctx can't identify the second genotype? Is there a way around this problem if my current dataset is too small? Notably, I didn't get this error when I ran the code on a larger version of the data that included multiple tissue samples from the same patient; due to the requirements of the project, however, it's necessary for me to subset the data by tissue type.

**Comment by GWW** [comment]
Hi,

I think there was a bug I had not encountered before while testing that showed up with your specific sample. I have fixed the bug.  Hopefully the rescue function works now. It should give you a plot that indicates to you if there are cells that "deviate" from the predominant genotype which would suggest that there is a second one present.  It will also try to identify that genotype.

**Comment by DLuong79** [comment]
I reinstalled sctx but I'm still getting the exact same error.

**Comment by GWW** [comment]
Sorry, I think there was a second bug I needed to fix.  Could you repull the repository again?  I hope this fixes the issue now.

**Comment by DLuong79** [comment]
Now there's a different error:

```
Only one genoptype found try rescue_genotype to find a second one
Rescued Label counts: (0 = 270) (3 = 4) 

Could not find a second potential genotype
cannot proceed only one genotype found
initial:  Counter({0: 270, 3: 4})

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], line 29
     25     print('cannot proceed only one genotype found')
     27 refine = RT.RefineGT(snv_data.strand_ref[keep].copy(), snv_data.strand_alt[keep].copy(), snv_data.snvs[keep].copy(), snv_data.barcodes, close_fig=False)
---> 29 if not refine.refine_genotypes(data._labels['initial_clustering'], out=None):
     30     print('Failed to identify a second genotype')
     32 df = pd.DataFrame({'barcode':refine._barcodes, 'label':refine._final_labels.copy(), 'gt1_score':refine._final_scores[:,0], 'gt2_score':refine._final_scores[:,1]})

File ~/anaconda3/envs/myenv/lib/python3.12/site-packages/sctx/refine.py:174, in RefineGT.refine_genotypes(self, rlabels, snv_min_cells_per_genotype, snv_total_cells, snv_AF_diff, eps, cell_min_snvs, cell_min_score, max_iterations, singlet_percentile, doublet_rate, doublet_simulate_multiplier, doublet_minimum, doublet_min_pval, seed, out)
    170 print('initial: ', Counter(labels))
    172 scats = []
--> 174 _, scores, passed, passed_snvs, gts = self._calculate_scores(labels)
    175 labels = NP.full(len(scores), 3, dtype='int')
    176 labels[passed] = NP.argmin(scores[passed], axis=1)

File ~/anaconda3/envs/myenv/lib/python3.12/site-packages/sctx/refine.py:84, in RefineGT._calculate_scores(self, labels)
     82 ogts = calc.calculate_genotypes(ref, alt, labels.astype('int32'))
     83 #print(Counter(labels))
---> 84 x, y = ogts['cells_0'], ogts['cells_1']
     85 p = self._params
     86 idx = NP.where((x >= p['snv_min_cells_per_genotype']) & (y >= p['snv_min_cells_per_genotype']) & ((x + y) >= p['snv_total_cells']))[0]

KeyError: 'cells_1'
```

**Comment by GWW** [comment]
That error basically means that even the rescue attempt could not find a second genotype.  The code following that function will not work.

Basically, It found 3 cells that had a slight deviation but not a large enough one to call it a second genotype Counter({0:270, 3:4}).  You can play with the thresholds for the rescue function.  You could lower the upper_mads from 10 to number above the lower_mads.  For example, `rescue_genotype(out=None, eps=1e-5, upper_mads=7, lower_mads=3)`.  You can see how the line placement in the resultant plot changes the results.   I have to warn you though setting the upper_mads to a value that's too low may just find nonsense genotypes.

There's a good chance that the sample you are looking at does not have enough cells to find a second genotype.

**Comment by DLuong79** [comment]
About upper_mads and lower_mads, what do they correspond to? I'm trying to adjust the sensitivity of sctx, as I'm currently testing it on non-transplanted samples and it's still detecting "second genotypes".

**Comment by GWW** [comment]
If a second genotype is not found through clustering, my algorithm will look for cells that look different than the average genotype across all of the cells.  The lower_mad is used to define a cutoff for the major genotype, where cells that have a genotype divergence from the average genotype less than (median(genotype divergence) + x*MAD). Analogously, the upper cutoff defines the group of cells that are initially assigned to the second genotype prior to refinement,  The cells between the two cutoffs aren't assigned but will likely be assigned during refinement.  The goal of this is to find a small number of cells that look very different than the average genotype.  If you make the upper mad parameter too low you will almost always find a second genotype and then the refinement step will force it.

**Comment by DLuong79** [comment]
Sometimes sctx identifies multiple "genotypes" even without running rescue_genotype; what do snv_cutoff and cell_cutoff correspond to so that I can adjust the cutoff values?

**Comment by GWW** [comment]
This removes cells with low numbers of co-expressed SNVs with other cells.  In the case of the default parameters, we required 20 co-expressed SNVs and each of these co-expressed SNVs should be expressed with at least 25 other cells.   This removes cases where cells have a handful of private SNVs force them to appear further apart than they are.

Just a note sctx, like other genotype deconvolution tools was not designed to be used on samples where a second genotype is not present.  It will probably find a second genotype, however, the genotype score differences between genotype 1 and 2 will likely be smaller than the case of a sample with multiple genotypes.  Moreover, the number of genotype specific SNVs tends to be small and in specific regions.  It will be difficult to tweak the parameters of these algorithms to not find a second genotype when isn't there and these parameter choices will likely affect your sensitivity for samples that do have a second genotype.

**Comment by GWW** [comment]
Note, there is a good example of poor SNV differences in [Figure 5](https://www.frontiersin.org/files/Articles/1161146/frtra-02-1161146-HTML/image_m/frtra-02-1161146-g005.jpg) of the scTX manuscript.

**Comment by DLuong79** [comment]
Is it possible to display the poor SNV differences as a numerical value, particularly if cell annotation data is unavailable?

**Comment by GWW** [comment]
You can just make a barcode map that maps every barcode to the same label.  It will still separate the samples by genotype.  You can probably look at the average between genotype and within genotype distance.

**Comment by DLuong79** [comment]
How do I retrieve the data related to "between genotype distance" and "within genotype distance"? Do I just use the gt1/2 scores?

**Comment by GWW** [comment]
Yes you can try those.  Examining the SNV heatmap is also helpful in this case.  The number of SNV's differing between the two genotypes may be indicative of a low quality second genotype depending on what the samples are.

**Comment by DLuong79** [comment]
I guess what I'm really asking for is a way to automatically discard low-quality genotypes using numerical data from the output of the FindSNVs, score_snvs, and find_predictive functions, without having to "eyeball" a heatmap.
